### ISSUE TITLE
Docs update: SIS TS Documentation for Onboarding

### ISSUE THREAD

**Issue by ParthS007** [cern-sis/issues#71]
We have current structure like this: [Gitlab](https://scientific-information-service.web.cern.ch/SIS-TS.%20Tools%20%26%20Services/Academia/)

- [ ] Introduction
- [ ] Academia
- [ ] Meetings
- [ ] Roles and Responsibilities
- [ ] Useful Links
- [ ] Welcome docs
- [ ] Software Development

The plan is to come up with a improved structure after feedbacks.

- [ ] Tools and Services
  - [ ] Projects
  - [ ] Roles and Responsibilities
  - [ ] Meetings
  
- [ ] Software Development
  - [ ] Contributing guidelines
  - [ ] Academia
  - [ ] Infrastructure

**Comment by MJedr** [comment]
Could you add this to useful links https://inspire.docs.cern.ch/?
